---
version: 3

images:
  base_image:
    name: registry.fedoraproject.org/fedora:40

dependencies:
  python_interpreter:
    package_system: python311
    python_path: /usr/bin/python3.11

  ansible_core:
    package_pip: ansible-core<2.17.0

  ansible_runner:
    package_pip: ansible-runner

  galaxy: requirements.yml

  python: requirements.txt
